recipes_data = [
    {
        "name": "Paneer Butter Masala",
        "is_veg": True,
        "cooking_time_minutes": 35,
        "instructions": "Heat butter and saute onion and garlic.\nAdd tomato puree and cook until oil separates.\nAdd spices, paneer cubes, and cream.\nSimmer for 5-7 minutes and serve hot.",
        "ingredients": ["paneer", "tomato", "butter", "cream", "onion", "garlic"],
    },
    {
        "name": "Aloo Gobi",
        "is_veg": True,
        "cooking_time_minutes": 30,
        "instructions": "Saute onion with cumin and turmeric.\nAdd potato and cauliflower with salt.\nCook covered until tender.\nFinish with coriander and serve.",
        "ingredients": ["potato", "cauliflower", "onion", "turmeric", "cumin"],
    },
    {
        "name": "Chicken Curry",
        "is_veg": False,
        "cooking_time_minutes": 45,
        "instructions": "Saute onion, garlic, and ginger.\nAdd tomato and spices, cook to thick masala.\nAdd chicken and cook until sealed.\nAdd water and simmer until chicken is tender.",
        "ingredients": ["chicken", "onion", "tomato", "garlic", "ginger"],
    },
    {
        "name": "Egg Curry",
        "is_veg": False,
        "cooking_time_minutes": 25,
        "instructions": "Boil and peel eggs.\nPrepare onion-tomato masala with chili and garam masala.\nAdd eggs and simmer in gravy for 8-10 minutes.\nServe with rice or roti.",
        "ingredients": ["egg", "onion", "tomato", "chili", "garam masala"],
    },
    {
        "name": "Tomato Onion Stir Fry",
        "is_veg": True,
        "cooking_time_minutes": 15,
        "instructions": "Heat oil and saute onion.\nAdd chopped tomato and salt.\nCook until soft and slightly dry.\nServe as side dish.",
        "ingredients": ["tomato", "onion", "oil", "salt"],
    },
    {
        "name": "Jeera Aloo",
        "is_veg": True,
        "cooking_time_minutes": 25,
        "instructions": "Boil and cube potato.\nTemper cumin in oil and add ginger.\nAdd potato, salt, chili powder, and turmeric.\nSaute until crisp and serve.",
        "ingredients": ["potato", "cumin", "oil", "salt", "ginger", "turmeric", "chili"],
    },
    {
        "name": "Aloo Matar",
        "is_veg": True,
        "cooking_time_minutes": 30,
        "instructions": "Saute onion and ginger-garlic paste.\nAdd tomato and spices.\nAdd potato and peas, then water.\nCook until soft and serve.",
        "ingredients": ["potato", "peas", "onion", "tomato", "garlic", "ginger", "turmeric"],
    },
    {
        "name": "Gobi Masala",
        "is_veg": True,
        "cooking_time_minutes": 28,
        "instructions": "Blanch cauliflower florets.\nCook onion-tomato masala with spices.\nAdd cauliflower and cook covered.\nFinish with garam masala.",
        "ingredients": ["cauliflower", "onion", "tomato", "garam masala", "turmeric", "oil"],
    },
    {
        "name": "Cabbage Poriyal",
        "is_veg": True,
        "cooking_time_minutes": 20,
        "instructions": "Temper mustard seeds and curry leaves.\nAdd onion and chopped cabbage.\nAdd salt and turmeric.\nCook uncovered till tender.",
        "ingredients": ["cabbage", "onion", "mustard seeds", "turmeric", "oil", "salt"],
    },
    {
        "name": "Capsicum Masala",
        "is_veg": True,
        "cooking_time_minutes": 22,
        "instructions": "Saute onion and garlic.\nAdd chopped capsicum and tomato.\nAdd chili powder, turmeric, and salt.\nCook till soft and serve.",
        "ingredients": ["capsicum", "onion", "tomato", "garlic", "turmeric", "chili", "salt"],
    },
    {
        "name": "Baingan Bharta",
        "is_veg": True,
        "cooking_time_minutes": 35,
        "instructions": "Roast eggplant and peel skin.\nSaute onion, garlic, and tomato.\nMash eggplant into masala.\nCook for 8-10 minutes and serve.",
        "ingredients": ["eggplant", "onion", "tomato", "garlic", "oil", "chili", "salt"],
    },
    {
        "name": "Mix Veg Curry",
        "is_veg": True,
        "cooking_time_minutes": 35,
        "instructions": "Prepare onion-tomato masala.\nAdd carrot, peas, potato, and cauliflower.\nAdd spices and water.\nCook till vegetables are tender.",
        "ingredients": ["carrot", "peas", "potato", "cauliflower", "onion", "tomato", "garam masala"],
    },
    {
        "name": "Veg Pulao",
        "is_veg": True,
        "cooking_time_minutes": 30,
        "instructions": "Saute whole spices with onion.\nAdd vegetables and basmati rice.\nAdd water and salt.\nCook until rice is fluffy.",
        "ingredients": ["rice", "onion", "carrot", "peas", "cinnamon", "cloves", "cardamom", "salt"],
    },
    {
        "name": "Tomato Rice",
        "is_veg": True,
        "cooking_time_minutes": 25,
        "instructions": "Saute onion and garlic in oil.\nAdd tomato puree and spices.\nAdd cooked rice and mix well.\nSimmer for 5 minutes.",
        "ingredients": ["rice", "tomato", "onion", "garlic", "turmeric", "oil", "salt"],
    },
    {
        "name": "Lemon Rice",
        "is_veg": True,
        "cooking_time_minutes": 20,
        "instructions": "Temper mustard seeds and curry leaves.\nAdd turmeric and cooked rice.\nAdd lemon juice and salt.\nMix and serve warm.",
        "ingredients": ["rice", "lemon", "mustard seeds", "turmeric", "oil", "salt"],
    },
    {
        "name": "Rajma Masala",
        "is_veg": True,
        "cooking_time_minutes": 50,
        "instructions": "Cook soaked rajma until soft.\nPrepare onion-tomato gravy with ginger and garlic.\nAdd rajma and simmer.\nServe with rice.",
        "ingredients": ["rajma", "onion", "tomato", "garlic", "ginger", "garam masala", "salt"],
    },
    {
        "name": "Chana Masala",
        "is_veg": True,
        "cooking_time_minutes": 40,
        "instructions": "Cook chickpeas until soft.\nCook onion-tomato masala with spices.\nAdd chickpeas and simmer for 15 minutes.\nServe with roti or rice.",
        "ingredients": ["chickpeas", "onion", "tomato", "garlic", "ginger", "cumin", "chili"],
    },
    {
        "name": "Dal Tadka",
        "is_veg": True,
        "cooking_time_minutes": 30,
        "instructions": "Boil toor dal with turmeric.\nPrepare tadka with garlic, chili, and cumin.\nMix tadka into dal.\nSimmer and serve.",
        "ingredients": ["toor dal", "turmeric", "garlic", "cumin", "chili", "salt", "oil"],
    },
    {
        "name": "Moong Dal Fry",
        "is_veg": True,
        "cooking_time_minutes": 25,
        "instructions": "Cook moong dal till soft.\nSaute onion, tomato, ginger, and garlic.\nAdd dal and spices.\nSimmer for 5-7 minutes.",
        "ingredients": ["moong dal", "onion", "tomato", "ginger", "garlic", "turmeric", "salt"],
    },
    {
        "name": "Palak Paneer",
        "is_veg": True,
        "cooking_time_minutes": 30,
        "instructions": "Blanch spinach and blend to puree.\nSaute onion, garlic, and tomato.\nAdd spinach puree and spices.\nAdd paneer cubes and simmer.",
        "ingredients": ["spinach", "paneer", "onion", "tomato", "garlic", "cream", "garam masala"],
    },
    {
        "name": "Methi Aloo",
        "is_veg": True,
        "cooking_time_minutes": 25,
        "instructions": "Saute potato until half-cooked.\nAdd methi leaves and spices.\nCook until potato is soft.\nServe hot with roti.",
        "ingredients": ["potato", "methi", "turmeric", "chili", "oil", "salt"],
    },
    {
        "name": "Bhindi Masala",
        "is_veg": True,
        "cooking_time_minutes": 25,
        "instructions": "Saute okra until non-sticky.\nCook onion-tomato masala separately.\nMix okra with masala and spices.\nCook 5 minutes and serve.",
        "ingredients": ["okra", "onion", "tomato", "turmeric", "chili", "garam masala", "oil"],
    },
    {
        "name": "Mushroom Masala",
        "is_veg": True,
        "cooking_time_minutes": 25,
        "instructions": "Saute onion, garlic, and ginger.\nAdd tomato and spices.\nAdd mushrooms and cook until soft.\nFinish with cream.",
        "ingredients": ["mushroom", "onion", "tomato", "garlic", "ginger", "cream", "garam masala"],
    },
    {
        "name": "Fish Curry",
        "is_veg": False,
        "cooking_time_minutes": 35,
        "instructions": "Marinate fish with turmeric and salt.\nCook onion-tomato gravy with garlic and ginger.\nAdd fish and simmer gently.\nServe hot with rice.",
        "ingredients": ["fish", "onion", "tomato", "garlic", "ginger", "turmeric", "salt"],
    },
]
